"use client";

import Image from "next/image";
import { useState, useEffect } from "react";

const Galary = () => {
  // Array of image objects from 1 to 16
  const initialImages = Array.from({ length: 16 }, (_, i) => ({
    id: i + 1,
    src: `/Images/galary${i + 1}.jpg`,
    alt: `Gallery image ${i + 1}`,
  }));

  // State to hold the shuffled images
  const [images, setImages] = useState(initialImages);

  // Function to shuffle array
  const shuffleImages = (array) => {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
  };

  // Effect to shuffle images every 5 seconds
  useEffect(() => {
    const interval = setInterval(() => {
      setImages((prevImages) => shuffleImages(prevImages));
    }, 5000); // Shuffle every 5 seconds

    // Cleanup interval on component unmount
    return () => clearInterval(interval);
  }, []);

  return (
    <section className="py-16">
      <div className="container mx-auto px-6 md:px-10 lg:px-16">
        {/* Title */}
        <h2 className="text-4xl md:text-5xl font-extrabold text-center mb-12 tracking-tight text-white">
          <span className="bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-cyan-500">
            Inspiration Gallery
          </span>
        </h2>

        {/* Gallery Container */}
        <div className="columns-1 sm:columns-2 md:columns-3 lg:columns-4 gap-6">
          {images.map((image) => (
            <div
              key={image.id}
              className={`group relative overflow-hidden rounded-xl bg-gray-800/50 backdrop-blur-md border 
                border-gray-700/30 hover:border-purple-500/60 hover:shadow-xl transition-all duration-500 
                mb-6 break-inside-avoid transform-gpu motion-safe:animate-float`}
            >
              {/* Image */}
              <Image
                src={image.src}
                alt={image.alt}
                width={0} 
                height={0} 
                sizes="100vw"
                className="w-full h-auto object-cover transition-transform duration-500 group-hover:scale-105"
              />
              {/* Overlay Effect */}
              <div className="absolute inset-0 bg-gradient-to-t from-purple-500/20 to-cyan-500/20 opacity-0 
                group-hover:opacity-100 transition-opacity duration-500 pointer-events-none"
              />
            </div>
          ))}
        </div>

        {/* Note */}
        <p className="text-center text-gray-400/70 text-sm mt-8">
          <strong>Note:</strong> These are placeholder images for UI purposes only, not generated by this model.
        </p>
      </div>
    </section>
  );
};

export default Galary;
